### ISSUE TITLE
are there any more parameters?

### ISSUE THREAD

**Issue by code-trekker** [svaante/decision-tree-id3#6]
Was using this library and I noticed that there aren't parameters in the documentation for `Id3Estimator()`. Are there any parameters that we can set? Maybe something similar to sklearn's `DecisionTreeClassifier()` where you can choose max_depth, criterion, etc.

**Comment by svaante** [comment]
If you look at the [documentation](https://svaante.github.io/decision-tree-id3/id3.html) the following parameters are present.
```python
""""

    Parameters
    ----------
    max_depth : int, optional
        max depth of features.
    min_samples_split : int, optional (default=2)
        min samples to split on.
    prune : bool, optional (default=False)
        set to True to prune the tree.
    gain_ratio : bool, optional (default=False)
        use gain ratio on split calculations.
    is_repeating: bool, optional (default=False)
        use repeating features.
""""
```
